#!/bin/bash
source config.shlib
helptxt() {
    echo -e ' -h | вывод помощи по ключам \n -c | принять на вход конфиг \n -p | режим фотографирования \n -v | режим видеосъемки \n -s | режим стрима \n -o | файл \n'
    echo 'Возможные устройства:'
    v4l2-ctl --list-devices
}

for i in $(seq 1 9); do
    if [[ "${!i}" = "-c" ]]; then
        i=$(( i + 1 ))
        photo="$(config_get ${!i} photo)"
        video="$(config_get ${!i} video)"
        stream="$(config_get ${!i} stream)"
        device="$(config_get ${!i} device)"
        output="$(config_get ${!i} output)"
    fi
done

while [[ -n "$1" ]]; do
    case "$1" in
    -p) photo=true ;;
    -v) video=true ;;
    -o) output=$2
        shift ;;
    -d) device=$2
        shift ;;
    -c) shift ;;
    -s) stream=true ;;
    --) shift
        break ;;
    *) helptxt ;;
    esac
    shift
done

if [[ -z $device ]] && [[ -z $stream ]] && [[ -n $1 ]]; then
    device=/dev/video0
    echo "Используется устройство по умолчанию - /dev/video0"
    echo "Другие варианты:"
    v4l2-ctl --list-devices
fi

if [[ $photo ]] && [[ $output ]]; then
    ffmpeg -hide_banner -loglevel error -f v4l2 -i $device -vframes 1 $output
    echo "Фото снято"
elif [[ $photo ]]; then
    ffmpeg -hide_banner -loglevel error -f v4l2 -i $device -vframes 1 photo.png
    echo "Фото снято"

elif [[ $video ]] && [[ $output ]]; then
    echo 'Нажмите q, чтобы завершить'
    ffmpeg -hide_banner -loglevel error -f v4l2 -r 30 -s 1920x1080 -i $device $output
    ffplay $device
    echo "Видео снято"
elif [[ $video ]]; then
    echo 'Нажмите q, чтобы завершить'
    ffmpeg -hide_banner -loglevel error -f v4l2 -framerate 30 -video_size 1920x1080 -i $device video.mp4
    ffplay $device
    echo "Видео снято"

elif [[ $stream ]]; then
    sdevice=$(v4l2-ctl --list-devices | awk '/v4l2/ { getline; print $1}')
    if [[ $XDG_BACKEND = "wayland" ]]; then
        echo "Нажмите Ctrl+C, чтобы завершить"
        wf-recorder --muxer=v4l2 --codec=rawvideo -t --file=/dev/video2 -x yuv420pq
    else
        echo "Нажмите Ctrl+C, чтобы завершить"
        ffmpeg -f x11grab -select_region 1 -show_region 1 -framerate 25 -i $DISPLAY -vf format=yuv420p -f v4l2 /dev/video2
    fi
fi
